---
galaxy_info:
  author: dbtools team
  description: Configure shell and git settings for development
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: EL
      versions:
        - "8"
        - "9"

dependencies: []

collections:
  - community.general
