databaseChangeLog:
  - changeSet:
      id: 20251114-01-create-demo
      author: sample
      changes:
        - createTable:
            tableName: demo_items
            columns:
              - column:
                  name: id
                  type: bigint
                  constraints:
                    primaryKey: true
              - column:
                  name: name
                  type: varchar(100)
