---
galaxy_info:
  author: David Pham
  description: Manage Windows service account user rights assignments
  company:

  license: MIT

  min_ansible_version: "2.10"

  platforms:
    - name: Windows
      versions:
        - 2016
        - 2019
        - 2022

  galaxy_tags:
    - windows
    - security
    - user_rights
    - sql_server
    - service_account

dependencies: []
