services:
  api:
    image: ealen/echo-server:latest
    ports:
      - "5000:80"
  web:
    image: nginxdemos/hello:latest
    ports:
      - "8080:80"
    depends_on:
      - api
networks:
  default:
    name: app-net
    driver: bridge
