services:
  hammerdb:
    build:
      context: ../..
      dockerfile: docker/hammerdb/Dockerfile
      args:
        REGISTRY_PREFIX: ${REGISTRY_PREFIX:-docker.io/library/}
    container_name: hammerdb
    stdin_open: true
    tty: true
    volumes:
      - ./hammerdb/scripts:/benchmarks
    networks:
      - devcontainer-network

networks:
  devcontainer-network:
    external: true
