services:
  hammerdb:
    build:
      context: /workspaces/dbtools
      dockerfile: docker/hammerdb/Dockerfile
    container_name: hammerdb
    stdin_open: true
    tty: true
    volumes:
      - ./hammerdb/scripts:/benchmarks
    networks:
      - devcontainer-network

networks:
  devcontainer-network:
    external: true
