---
galaxy_info:
  author: dbtools team
  description: Install development tools (UV, NVM) for Linux environments
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: EL
      versions:
        - "8"
        - "9"

dependencies: []

