---
galaxy_info:
  role_name: mongodb_rhel
  namespace: gds
  author: dbtools team
  description: Configure RHEL for MongoDB following production best practices
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"

dependencies: []

collections:
  - ansible.posix
